title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # A blog on GitHub pages"
  This is short blog on different things that are possible using GitHub pages

# social links
github_username: BeamQueen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
